"""ARK95X ROI Engine — Data Banking & Leverage Operations
Tracks the financial value generated by the AI system:
  - Compute cost savings (local vs cloud API)
  - Agent productivity multiplier (vs human baseline)
  - Data asset valuation (memory vectors as balance sheet items)
  - Leverage ratio and compound growth projection
  - Self-funding threshold calculation
"""
import time
import math
import random
import logging
from typing import Dict, List, Optional
from dataclasses import dataclass, field

logger = logging.getLogger("ark95x.telemetry.roi")

# ── Market rate constants ──────────────────────────────────────────────────────
_CLOUD_COST_PER_REQUEST  = 0.0115   # GPT-4o avg blended $/request
_LOCAL_COST_PER_REQUEST  = 0.00009  # Ollama local (electricity only, $0.10/kWh)
_HUMAN_RATE_PER_HOUR     = 85.0     # $/hr skilled AI/dev worker equivalent
_VECTOR_UNIT_VALUE       = 0.08     # $/embedding (curated memory asset)
_SENSOR_STREAM_VALUE     = 0.22     # $/hour of CSI sensing data product
_LEVERAGE_MULTIPLIER_CAP = 24.0     # max leverage ratio cap


@dataclass
class LedgerEntry:
    date:            str
    compute_savings: float
    productivity:    float
    data_delta:      float
    total_value:     float
    cumulative:      float
    timestamp:       float = field(default_factory=time.time)


@dataclass
class DataAsset:
    name:       str
    category:   str   # "memory" | "sensing" | "model" | "agent_ip"
    units:      float
    unit_value: float
    total:      float = field(init=False)

    def __post_init__(self):
        self.total = self.units * self.unit_value


class ROIEngine:
    """
    Treats the AI system as a balance sheet.

    Assets:
      - Memory vectors (knowledge capital)
      - Sensing data streams (real-time data product)
      - Agent-generated IP (mission outputs)

    Revenue:
      - Compute cost savings (local vs cloud delta)
      - Productivity arbitrage (agent hours vs human rate)
      - Data product value (sensing streams sold/used)

    Leverage:
      - Investment = infrastructure + time
      - Return = all revenue streams
      - Self-funding threshold = break-even per day
    """

    def __init__(self, config: Optional[Dict] = None):
        self.config = config or {}
        self._ledger: List[LedgerEntry] = []
        self._cumulative = 0.0
        self._request_count = 0
        self._local_ratio = 0.73   # 73% local routing
        self._agent_hours = 0.0
        self._memory_vectors = 2847
        self._sensing_hours = 0.0
        self._tick = 0
        self._seed_ledger()

    # ── Public API ────────────────────────────────────────────────────────────

    def record_requests(self, count: int = 1, local: bool = True):
        self._request_count += count
        if local:
            savings = count * (_CLOUD_COST_PER_REQUEST - _LOCAL_COST_PER_REQUEST)
        else:
            savings = 0.0
        self._cumulative += savings

    def record_agent_work(self, hours: float):
        self._agent_hours += hours

    def record_sensing(self, hours: float):
        self._sensing_hours += hours
        self._memory_vectors += int(hours * 120)  # ~120 vectors/hour of sensing

    def tick(self) -> LedgerEntry:
        """Advance one time step and generate a ledger entry."""
        self._tick += 1
        t = self._tick * 0.12
        noise = lambda s=0.5: random.gauss(0, s)

        # Simulated daily metrics with realistic growth trend
        growth_trend = 1 + self._tick * 0.003
        compute_savings = max(0, (5.8 + math.sin(t) * 1.2 + noise(0.4)) * growth_trend)
        productivity   = max(0, (42.0 + math.cos(t * 0.7) * 8 + noise(2)) * growth_trend)
        data_delta     = max(0, (self._memory_vectors * _VECTOR_UNIT_VALUE / 30
                               + _SENSOR_STREAM_VALUE * 8 + noise(1)) * growth_trend)

        self._memory_vectors += int(random.uniform(2, 8))
        daily_total = compute_savings + productivity + data_delta
        self._cumulative += daily_total

        entry = LedgerEntry(
            date=f"Day {self._tick}",
            compute_savings=round(compute_savings, 2),
            productivity=round(productivity, 2),
            data_delta=round(data_delta, 2),
            total_value=round(daily_total, 2),
            cumulative=round(self._cumulative, 2),
        )
        self._ledger.append(entry)
        return entry

    def snapshot(self) -> Dict:
        if not self._ledger:
            for _ in range(3):
                self.tick()
        self.tick()
        last = self._ledger[-1]
        assets = self._build_assets()
        total_assets = sum(a.total for a in assets)
        daily_revenue = last.total_value
        leverage = min(_LEVERAGE_MULTIPLIER_CAP,
                       self._cumulative / max(self._infrastructure_cost(), 0.01))
        breakeven_days = self._infrastructure_cost() / max(daily_revenue, 0.01)
        return {
            "summary": {
                "cumulative_value":   round(self._cumulative, 2),
                "daily_revenue":      round(daily_revenue, 2),
                "total_assets":       round(total_assets, 2),
                "leverage_ratio":     round(leverage, 2),
                "breakeven_days":     round(breakeven_days, 1),
                "memory_vectors":     self._memory_vectors,
                "request_count":      self._request_count,
                "local_routing_pct":  round(self._local_ratio * 100, 1),
            },
            "breakdown": {
                "compute_savings": round(last.compute_savings, 2),
                "productivity":    round(last.productivity, 2),
                "data_value":      round(last.data_delta, 2),
            },
            "assets": [
                {"name": a.name, "category": a.category,
                 "units": round(a.units, 0), "unit_value": a.unit_value,
                 "total": round(a.total, 2)}
                for a in assets
            ],
            "projections": self._projections(daily_revenue),
        }

    def get_ledger(self, n: int = 30) -> List[Dict]:
        return [
            {"date": e.date, "compute": e.compute_savings, "productivity": e.productivity,
             "data": e.data_delta, "total": e.total_value, "cumulative": e.cumulative}
            for e in self._ledger[-n:]
        ]

    # ── Internal ──────────────────────────────────────────────────────────────

    def _build_assets(self) -> List[DataAsset]:
        return [
            DataAsset("Memory Knowledge Base", "memory",
                      self._memory_vectors, _VECTOR_UNIT_VALUE),
            DataAsset("Sensing Data Streams",  "sensing",
                      max(0, self._sensing_hours), _SENSOR_STREAM_VALUE),
            DataAsset("Agent Mission IP",      "agent_ip",
                      47.0, 12.50),
            DataAsset("Local Model Cache",     "model",
                      21.0, 8.00),
        ]

    def _infrastructure_cost(self) -> float:
        return 240.0  # $/month (compute infra estimate)

    def _projections(self, daily: float) -> Dict:
        return {
            "30d":  round(daily * 30 * 1.02, 2),
            "60d":  round(daily * 60 * 1.04, 2),
            "90d":  round(daily * 90 * 1.07, 2),
            "roi_30d_pct": round((daily * 30 / max(self._infrastructure_cost(), 1)) * 100, 1),
        }

    def _seed_ledger(self):
        self._cumulative = 0.0
        for i in range(27):
            self._tick = i
            t = i * 0.12
            noise = lambda s=0.4: random.gauss(0, s)
            gt = 1 + i * 0.003
            cs = max(0, (5.8 + math.sin(t) * 1.2 + noise()) * gt)
            pr = max(0, (42.0 + math.cos(t * 0.7) * 8 + noise(2)) * gt)
            dd = max(0, (self._memory_vectors * _VECTOR_UNIT_VALUE / 30
                        + _SENSOR_STREAM_VALUE * 8 + noise(1)) * gt)
            self._memory_vectors += int(random.uniform(2, 8))
            total = cs + pr + dd
            self._cumulative += total
            self._ledger.append(LedgerEntry(
                date=f"Day {i+1}",
                compute_savings=round(cs, 2),
                productivity=round(pr, 2),
                data_delta=round(dd, 2),
                total_value=round(total, 2),
                cumulative=round(self._cumulative, 2),
                timestamp=time.time() - (27-i) * 86400,
            ))
        self._tick = 27
