"""
council-ouroboros / workers/w1_drafter.py
W1 DRAFTER — pleading-shell + doc-prep generator.

Roster role: DRAFTER (Gemini lead, post-rotation 2026-05-18).

Top-3 templates (per Gemini DRAFTER vote @95 conf):
  1. Answer + Affirmative Defenses to Foreclosure Complaint
  2. Motion to Dismiss / Motion for More Definite Statement
  3. Standardized Request for Production of Documents + Interrogatories

Output: DOCX via docling pipeline (consumed downstream by W2 auditor).
All output stamped: "DOCUMENT PREPARATION ONLY — NOT LEGAL ADVICE.
MUST BE REVIEWED BY A LICENSED IOWA ATTORNEY BEFORE FILING."
"""
from __future__ import annotations
import os, logging, datetime as dt
from dataclasses import dataclass
from pathlib import Path
from router import Router
from council import ROSTER

log = logging.getLogger("w1_drafter")

TEMPLATE_DIR = Path(os.getenv("DOC_TEMPLATE_DIR", "./templates"))
OUTPUT_DIR   = Path(os.getenv("OUTPUT_DIR", "./out"))
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

UPL_DISCLAIMER = (
    "DOCUMENT PREPARATION ONLY — NOT LEGAL ADVICE. "
    "This draft was generated by an automated document-preparation system "
    "and MUST be reviewed and adopted by a licensed Iowa attorney before filing."
)

TEMPLATES = {
    "answer_affirmative_defenses": "foreclosure_answer.j2",
    "motion_to_dismiss":           "motion_to_dismiss.j2",
    "rfp_interrogatories":         "rfp_interrogatories.j2",
}

@dataclass
class Draft:
    draft_id: str
    lead_id: str
    template: str
    text: str
    citations: list[str]
    generated_at: str

async def _ask_drafter(prompt: str) -> str:
    """Route to Gemini DRAFTER via hybrid router; fallback to other SWING voters."""
    router = Router([v for v in ROSTER if v.role in ("DRAFTER", "SWING")])
    results = await router.broadcast(prompt)
    # prefer the DRAFTER role output if present
    for r in results:
        if r["role"] == "DRAFTER" and r["output"]:
            return r["output"]
    for r in results:
        if r["output"]:
            return r["output"]
    return ""

async def draft(lead: dict, template_key: str) -> Draft:
    if template_key not in TEMPLATES:
        raise ValueError(f"unknown template: {template_key}")
    prompt = (
        f"Draft a {template_key.replace('_',' ')} for an Iowa foreclosure matter. "
        f"Case facts: {lead}. Use Iowa Rules of Civil Procedure. "
        "Output: structured pleading text + JSON list of statutes/rules cited. "
        "DO NOT render legal advice; this is document preparation only."
    )
    text = await _ask_drafter(prompt)
    text = f"{UPL_DISCLAIMER}\n\n{text}"
    draft_obj = Draft(
        draft_id=f"{lead.get('lead_id','?')}-{template_key}",
        lead_id=lead.get("lead_id", "?"),
        template=template_key,
        text=text,
        citations=[],
        generated_at=dt.datetime.utcnow().isoformat() + "Z",
    )
    # persist to OUTPUT_DIR for W2 auditor pickup
    (OUTPUT_DIR / f"{draft_obj.draft_id}.txt").write_text(text, encoding="utf-8")
    log.info("drafted %s", draft_obj.draft_id)
    return draft_obj
